language: c
sudo: false
service: docker

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin/1.5.9
  matrix:
   - SCRIPT=clisp
   - SCRIPT=paip
   - SCRIPT=ccl-bin
   - SCRIPT=clasp
   - SCRIPT=libsigsegv
   - SCRIPT=libffcall
   - SCRIPT=asdf
   - SCRIPT=ecl
   - SCRIPT=release-roswell

os:
  - linux

cache:
  directories:
    - $HOME/.roswell

addons:
  apt:
    packages:
      - debhelper
      - dh-autoreconf
      - fakeroot

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then
     ros dist use quicklisp 2019-08-13;
     ros install snmsts/sn.github roswell/sbcl_bin lake prove;lake-tools dump;
    fi
  - if [ x$ADD_CACHE != x ] ; then ros install $ADD_CACHE ;fi

script:
  - cd $SCRIPT;lake
